"""Project-wide paths and dataset configuration."""

from pathlib import Path

CODE_DIR = Path(__file__).resolve().parents[1]
PROJECT_DIR = CODE_DIR.parent

DATASET_DIR = PROJECT_DIR / "dataset"
OUTPUTS_DIR = PROJECT_DIR / "outputs"

SEQUENCE_ID = "00"
SEQUENCE_DIR = DATASET_DIR / "sequences" / SEQUENCE_ID

CALIBRATION_PATH = SEQUENCE_DIR / "calib.txt"

EX3_OUTPUT_DIR = OUTPUTS_DIR / "ex3"
EX4_OUTPUT_DIR = OUTPUTS_DIR / "ex4"
EX5_OUTPUT_DIR = OUTPUTS_DIR / "ex5"
EX6_OUTPUT_DIR = OUTPUTS_DIR / "ex6"
EX7_OUTPUT_DIR = OUTPUTS_DIR / "ex7"
EX8_OUTPUT_DIR = OUTPUTS_DIR / "ex8"
FINAL_ANALYSIS_OUTPUT_DIR = OUTPUTS_DIR / "final_analysis"

CACHE_DIR = OUTPUTS_DIR / "cache"
FINAL_ANALYSIS_OUTPUT_DIR = OUTPUTS_DIR / "final_analysis"

DB_PATH = EX4_OUTPUT_DIR / "tracking_db"
GLOBAL_CAMERA_MATRICES_PATH = EX3_OUTPUT_DIR / "global_camera_matrices.npy"
GT_POSES_PATH = DATASET_DIR / "poses" / f"{SEQUENCE_ID}.txt"

LEFT_IMAGES_DIR = SEQUENCE_DIR / "image_0"
RIGHT_IMAGES_DIR = SEQUENCE_DIR / "image_1"

# ==============================================================================
# HYPERPARAMETERS
# ==============================================================================

# General
RANDOM_SEED = 42

# Feature Extraction
FEATURE_TYPE = "akaze"
NUM_FEATURES = 3000

# Feature Matching
RATIO_THRESHOLD = 0.85
DEVIATION_THRESHOLD = 2.0
STEREO_RATIO_THRESHOLD = 0.75

# Tracking & Database
MIN_TRACK_LENGTH = 2
MIN_TRACK_OBSERVATIONS = 2

# PnP & RANSAC
MAX_RANSAC_ITERATIONS = 2000
RANSAC_CONFIDENCE = 0.99
MEASUREMENT_SIGMA_PIXELS = 1.0
SUPPORTER_THRESHOLD_PIXELS = 2.0
MAX_TRANSLATION_PNP = 30.0
MIN_INLIERS_PNP = 6
PNP_SAMPLE_SIZE = 4
MAX_DEPTH = 300.0
MIN_DISPARITY = 0.5
MAX_PROJECTION_ERROR_DEFAULT = 100.0


# Bundle Adjustment Windows
BA_WINDOW_SIZE = 12
BA_OVERLAP = 1

# Loop Closure Candidates
MIN_KEYFRAME_SEPARATION = 5
KEYFRAME_STEP = 10
MAHALANOBIS_THRESHOLD = 32023.8

# Consensus Matching (PnP/RANSAC)
MIN_LOOP_INLIERS = 20
MIN_REPRESENTATIVE_LOOP_INLIERS = 30
NUM_LOOP_CLOSURE_REPRESENTATIVES = 10
MAX_REFINED_COVARIANCE_CONDITION = 100000000.0

# Relative Errors Analysis
MAX_DISTANCE = 50
MIN_GAP = 11
MAX_GAP = 20
MIN_TRANSLATION_M = 5.0
MAX_TRANSLATION_M = 5.0
MIN_ROTATION_DEG = 12.0
MAX_ROTATION_DEG = 20.0
TARGET_TRANSLATION_M = 5.0
TARGET_ROTATION_DEG = 12.0

# Refinement
SOURCE_POSE_PRIOR_SIGMA = 1e-9
